Feature/css reset
Commencis/starter-react-vite pull request #85
Opened 2024-12-17 11:14 UTC by abaturt

2024-12-17 12:13 UTC, ymehmetcan requested changes

2024-12-17 12:13 UTC, ymehmetcan commented on src/styles/base/_base.scss
> +  line-height: 1.5;
Aslında tüm reset/normalize ile ilgili style'ları `_reset.scss` veya `_normalize.scss` gibi bir dosyada tutsak, `_base.scss` tarafında project-specific base'leri alsak daha güzel olabilir.

Örneğin `body` tarafındaki bu `color` ve `font-family` project specific gibi düşünsek, diğerlerinin tamamı reset ise bunu ayırıp devamında `main.scss` en tepesinde `@use` yapabiliriz.

Base de proje devamında büyüyebilir, h tag'lerinin font-size'ları renkleri, `a` `text-decoration: none` vb buraya bir çok base gelebilir.

2024-12-20 06:43 UTC, amourreux approved these changes

2024-12-24 19:14 UTC, ymehmetcan approved these changes

2024-12-24 19:14 UTC, merged